[project]
name = "geography"
version = "0.1.0"
description = "Philippine language similarity project using geographical and historical analysis."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "geopandas>=1.1.1",
    "matplotlib>=3.10.6",
    "notebook>=7.4.7",
]
